export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const TEMPLATE_LIST_LOADING = 'TEMPLATE_LIST_LOADING'
export const TEMPLATE_LIST_SUCCESS = 'TEMPLATE_LIST_SUCCESS'
export const TEMPLATE_LIST_ERROR = 'TEMPLATE_LIST_ERROR'

export const TEMPLATE_ADD_LOADING = 'TEMPLATE_ADD_LOADING'
export const TEMPLATE_ADD_SUCCESS = 'TEMPLATE_ADD_SUCCESS'
export const TEMPLATE_ADD_ERROR = 'TEMPLATE_ADD_ERROR'

export const TEMPLATE_LOADING = 'TEMPLATE_LOADING'
export const TEMPLATE_SUCCESS = 'TEMPLATE_SUCCESS'
export const TEMPLATE_ERROR = 'TEMPLATE_ERROR'

export const PAGE_LOADING = 'PAGE_LOADING'
export const PAGE_SUCCESS = 'PAGE_SUCCESS'
export const PAGE_ERROR = 'PAGE_ERROR'

export const PAGE_ADD_LOADING = 'PAGE_ADD_LOADING'
export const PAGE_ADD_SUCCESS = 'PAGE_ADD_SUCCESS'
export const PAGE_ADD_ERROR = 'PAGE_ADD_ERROR'

export const PAGE_SWITCH = 'PAGE_SWITCH'

// export const PAGE_ADD_COMPONENT = 'PAGE_ADD_COMPONENT'
// export const PAGE_UPDATE_COMPONENT = 'PAGE_UPDATE_COMPONENT'

export const COMPONENT_LIST_LOADING = 'COMPONENTS_LIST_LOADING'
export const COMPONENT_LIST_SUCCESS = 'COMPONENT_LIST_SUCCESS'
export const COMPONENT_LIST_ERROR = 'COMPONENT_LIST_ERROR'

export const COMPONENT_ADD_LOADING = 'COMPONENT_ADD_LOADING'
export const COMPONENT_ADD_SUCCESS = 'COMPONENT_ADD_SUCCESS'
export const COMPONENT_ADD_ERROR = 'COMPONENT_ADD_ERROR'

export const COMPONENT_UPDATE_LOADING = 'COMPONENT_UPDATE_LOADING'
export const COMPONENT_UPDATE_SUCCESS = 'COMPONENT_UPDATE_SUCCESS'
export const COMPONENT_UPDATE_ERROR = 'COMPONENT_UPDATE_ERROR'

export const COMPONENT_UNDO_SUCCESS = 'COMPONENT_UNDO_SUCCESS'
export const COMPONENT_UNDO_ERROR = 'COMPONENT_UNDO_ERROR'
export const COMPONENT_REDO_SUCCESS = 'COMPONENT_REDO_SUCCESS'
export const COMPONENT_REDO_ERROR = 'COMPONENT_REDO_ERROR'
export const COMPONENT_FLUSH_HISTORY = 'COMPONENT_FLUSH_HISTORY'
export const COMPONENT_INIT_HISTORY = 'COMPONENT_INIT_HISTORY'

export const WIDGET_LIST_LOADING = 'WIDGET_LIST_LOADING'
export const WIDGET_LIST_SUCCESS = 'WIDGET_LIST_SUCCESS'
export const WIDGET_LIST_ERROR = 'WIDGET_LIST_ERROR'

export const WIDGET_ADD_LOADING = 'WIDGET_ADD_LOADING'
export const WIDGET_ADD_SUCCESS = 'WIDGET_ADD_SUCCESS'
export const WIDGET_ADD_ERROR = 'WIDGET_ADD_ERROR'

export const WIDGET_UPDATE_LOADING = 'WIDGET_UPDATE_LOADING'
export const WIDGET_UPDATE_SUCCESS = 'WIDGET_UPDATE_SUCCESS'
export const WIDGET_UPDATE_ERROR = 'WIDGET_UPDATE_ERROR'

export const UPDATE_CANVAS = 'UPDATE_CANVAS'
