export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const TEMPLATE_LIST_LOADING = 'TEMPLATE_LIST_LOADING'
export const TEMPLATE_LIST_SUCCESS = 'TEMPLATE_LIST_SUCCESS'
export const TEMPLATE_LIST_ERROR = 'TEMPLATE_LIST_ERROR'

export const TEMPLATE_LOADING = 'TEMPLATE_LOADING'
export const TEMPLATE_SUCCESS = 'TEMPLATE_SUCCESS'
export const TEMPLATE_ERROR = 'TEMPLATE_ERROR'

export const PAGE_LOADING = 'PAGE_LOADING'
export const PAGE_SUCCESS = 'PAGE_SUCCESS'
export const PAGE_ERROR = 'PAGE_ERROR'
export const PAGE_ADD_COMPONENT = 'PAGE_ADD_COMPONENT'
export const PAGE_UPDATE_COMPONENT = 'PAGE_UPDATE_COMPONENT'
export const TEMPLATE_SWITCH_PAGE = 'TEMPLATE_SWITCH_PAGE'

export const UPDATE_CANVAS = 'UPDATE_CANVAS'
